service:
  name: my-magic-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  api:
    handler: src/handler.images
    events:
      - http:
          method: get
          path: images
